const houses = [
  {
    addressLineOne: "35 Longhorn Road",
    town: "Tenterden",
    postalCode: "TN30 5RH",
    propertyType: "Detatached",
    beds: 5,
    baths: 3,
    price: 1350000,
    isSold: false,
    photo: "/houses/house1.jpeg",
  },
  {
    addressLineOne: "21 Woodbury Lane",
    town: "Clapham",
    postalCode: "SW4 9NQ",
    propertyType: "Detatached",
    beds: 6,
    baths: 4,
    price: 1450000,
    isSold: false,
    photo: "/houses/house2.jpeg",
  },
  {
    addressLineOne: "5 The Willows",
    town: "Canterbury",
    postalCode: "CT1 2PX",
    propertyType: "Detached",
    beds: 4,
    baths: 2,
    price: 1180000,
    isSold: true,
    photo: "/houses/house3.jpg",
  },
  {
    addressLineOne: "Flat 12 Marina Court",
    town: "Margate",
    postalCode: "CT9 1QW",
    propertyType: "Detatched",
    beds: 4,
    baths: 3,
    price: 795000,
    isSold: false,
    photo: "/houses/house4.jpg",
  },
  {
    addressLineOne: "42 Church Lane",
    town: "Ashford",
    postalCode: "TN23 1RD",
    propertyType: "Terraced",
    beds: 3,
    baths: 2,
    price: 985000,
    isSold: false,
    photo: "/houses/house5.jpg",
  },
  {
    addressLineOne: "8 Victoria Gardens",
    town: "Dover",
    postalCode: "CT16 1EP",
    propertyType: "Semi-detached",
    beds: 3,
    baths: 2,
    price: 875000,
    isSold: true,
    photo: "/houses/house6.jpg",
  },
  {
    addressLineOne: "The Old Rectory",
    town: "Sandwich",
    postalCode: "CT13 9JH",
    propertyType: "Detached",
    beds: 5,
    baths: 3,
    price: 825000,
    isSold: false,
    photo: "/houses/house7.jpg",
  },
  {
    addressLineOne: "15 Mill Road",
    town: "Folkestone",
    postalCode: "CT19 4AX",
    propertyType: "Detached",
    beds: 4,
    baths: 2,
    price: 1050000,
    isSold: true,
    photo: "/houses/house8.jpg",
  },
  {
    addressLineOne: "Penthouse 1, Harbour View",
    town: "Whitstable",
    postalCode: "CT5 1BG",
    propertyType: "Detached",
    beds: 5,
    baths: 3,
    price: 995000,
    isSold: false,
    photo: "/houses/house9.jpg",
  },
  {
    addressLineOne: "4 Oak Tree Close",
    town: "Sevenoaks",
    postalCode: "TN13 2YU",
    propertyType: "Detached",
    beds: 4,
    baths: 3,
    price: 1550000,
    isSold: false,
    photo: "/houses/house10.jpg",
  },
];

export default houses;
