import {
  generateRandomFaceMale,
  generateRandomFaceFemale,
} from "../../../helpers/generateRandomFace";

export const users = [
  {
    id: 1,
    name: "John Smith",
    jobTitle: "Senior HR Manager",
    role: "Admin",
    photo: generateRandomFaceMale(),
    bio: "Experienced HR professional with 8+ years in talent management and organizational development. Passionate about creating inclusive workplace cultures. Successfully implemented onboarding programs that reduced new hire turnover by 35% and established mentorship programs connecting senior staff.",
    phone: `+44 7700 900${Math.floor(Math.random() * 999)}`,
    email: "john.smith@company.com",
    department: "Human Resources",
    skills: [
      "Talent Management",
      "Employee Relations",
      "Performance Reviews",
      "Compliance",
    ],
    startDate: "2020-03-15",
    status: "Online",
    manager: null, // Top-level manager
  },
  {
    id: 2,
    name: "Sophie Reynolds",
    jobTitle: "Senior Product Designer",
    role: "Member",
    photo: generateRandomFaceFemale(),
    bio: "Creative designer focused on user-centered design and accessibility. Led redesign of the main product dashboard resulting in 40% improved user engagement. Brings 6 years of design experience with expertise in design systems and component libraries.",
    phone: `+44 7700 900${Math.floor(Math.random() * 999)}`,
    email: "sophie.reynolds@company.com",
    department: "Product",
    skills: [
      "UI/UX Design",
      "Prototyping",
      "User Research",
      "Figma",
      "Design Systems",
    ],
    startDate: "2021-06-20",
    status: "Online",
    manager: 1,
  },
  {
    id: 3,
    name: "Mary Williams",
    jobTitle: "Talent Acquisition Specialist",
    role: "Member",
    photo: generateRandomFaceFemale(),
    bio: "Results-driven recruiter specializing in technical roles. Successfully filled 95% of open positions within target timeframes in 2023. Built strong relationships with top engineering schools and maintains an active network of over 2,000 technical professionals.",
    phone: `+44 7700 900${Math.floor(Math.random() * 999)}`,
    email: "mary.williams@company.com",
    department: "Human Resources",
    skills: [
      "Technical Recruiting",
      "Interviewing",
      "Candidate Sourcing",
      "LinkedIn Recruiting",
    ],
    startDate: "2022-01-10",
    status: "Away",
    manager: 1,
  },
  {
    id: 4,
    name: "Mark Jenkins",
    jobTitle: "Design Engineer",
    role: "Member",
    photo: "",
    bio: "Full-stack engineer with a design background. Bridges the gap between design and development teams to create pixel-perfect user interfaces. Has contributed to the company's design system library, creating reusable React components that maintain design consistency while improving development velocity.",
    phone: `+44 7700 900${Math.floor(Math.random() * 999)}`,
    email: "mark.jenkins@company.com",
    department: "Engineering",
    skills: [
      "React",
      "TypeScript",
      "CSS",
      "Design Systems",
      "Next.js",
      "Figma",
    ],
    startDate: "2021-09-05",
    status: "Online",
    manager: 6, // Reports to Sarah Chen
  },
  {
    id: 5,
    name: "Alex Thompson",
    jobTitle: "Sales Director",
    role: "Manager",
    photo: generateRandomFaceMale(),
    bio: "Strategic sales leader with proven track record of exceeding targets. Built and scaled the enterprise sales team from 2 to 12 representatives. Brings 12 years of B2B SaaS sales experience with expertise in complex enterprise deals and multi-stakeholder negotiations.",
    phone: `+44 7700 900${Math.floor(Math.random() * 999)}`,
    email: "alex.thompson@company.com",
    department: "Sales",
    skills: [
      "Enterprise Sales",
      "Team Leadership",
      "CRM Management",
      "Contract Negotiation",
    ],
    startDate: "2019-11-12",
    status: "Out of Office",
    manager: 1,
  },
  {
    id: 6,
    name: "Sarah Chen",
    jobTitle: "Engineering Manager",
    role: "Manager",
    photo: generateRandomFaceFemale(),
    bio: "Technical leader managing a team of 8 engineers. Former senior developer with expertise in scalable web applications and team mentorship. Successfully led migration of legacy systems to modern cloud architecture, reducing infrastructure costs by 40% while improving system reliability.",
    phone: `+44 7700 900${Math.floor(Math.random() * 999)}`,
    email: "sarah.chen@company.com",
    department: "Engineering",
    skills: [
      "Team Management",
      "JavaScript",
      "System Architecture",
      "Agile Methodologies",
    ],
    startDate: "2020-07-01",
    status: "Offline",
    manager: 1,
  },
  {
    id: 7,
    name: "David Rodriguez",
    jobTitle: "Customer Success Manager",
    role: "Member",
    photo: "",
    bio: "Customer-focused professional dedicated to ensuring client satisfaction and retention. Maintains a 98% customer satisfaction rating across portfolio of 50+ enterprise accounts. Developed the company's customer health scoring system that proactively identifies at-risk accounts, reducing churn by 25%.",
    phone: `+44 7700 900${Math.floor(Math.random() * 999)}`,
    email: "david.rodriguez@company.com",
    department: "Customer Success",
    skills: [
      "Customer Relations",
      "Account Management",
      "Problem Solving",
      "Product Training",
    ],
    startDate: "2022-04-18",
    status: "Online",
    manager: 1,
  },
  {
    id: 8,
    name: "Emma Foster",
    jobTitle: "Marketing Specialist",
    role: "Member",
    photo: generateRandomFaceFemale(),
    bio: "Digital marketing expert specializing in content strategy and social media. Increased organic traffic by 150% through SEO optimization initiatives. Manages the company blog which generates 40% of marketing qualified leads and built social media presence with 300% increased engagement.",
    phone: `+44 7700 900${Math.floor(Math.random() * 999)}`,
    email: "emma.foster@company.com",
    department: "Marketing",
    skills: [
      "Content Marketing",
      "SEO",
      "Social Media",
      "Analytics",
      "Email Marketing",
    ],
    startDate: "2023-02-14",
    status: "Online",
    manager: 9,
  },
  {
    id: 9,
    name: "Michael Park",
    jobTitle: "Marketing Director",
    role: "Manager",
    photo: generateRandomFaceMale(),
    bio: "Growth-focused marketing leader with 10+ years experience in B2B SaaS. Led successful product launches and rebranding initiatives that increased brand awareness by 200%. Built marketing teams from the ground up at three different SaaS companies with expertise spanning demand generation and product marketing.",
    phone: `+44 7700 900${Math.floor(Math.random() * 999)}`,
    email: "michael.park@company.com",
    department: "Marketing",
    skills: [
      "Growth Marketing",
      "Brand Strategy",
      "Product Marketing",
      "Team Leadership",
    ],
    startDate: "2019-08-30",
    status: "Busy",
    manager: 1,
  },
  {
    id: 10,
    name: "Lisa Anderson",
    jobTitle: "Backend Developer",
    role: "Member",
    photo: generateRandomFaceFemale(),
    bio: "Experienced backend engineer focused on building robust APIs and scalable microservices. Reduced system response times by 60% through optimization while maintaining 99.95% uptime. Led migration from monolithic to microservices architecture, improving deployment frequency from monthly to daily releases.",
    phone: `+44 7700 900${Math.floor(Math.random() * 999)}`,
    email: "lisa.anderson@company.com",
    department: "Engineering",
    skills: [
      "Node.js",
      "Python",
      "Database Design",
      "API Development",
      "Cloud Architecture",
    ],
    startDate: "2022-10-03",
    status: "Away",
    manager: 6,
  },
];
